on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

name: Build

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd sjtutex && l3build ctan
        name: build package with l3build
      - name: prepare upload artifacts
        run: |
          unzip -l sjtutex/build/distrib/tds/sjtutex.tds.zip
          sudo rm sjtutex/build/distrib/tds/sjtutex.tds.zip
      - uses: actions/upload-artifact@v2
        with:
          path: |
            sjtutex/build/distrib/tds/
          name: sjtutex.tds
        name: upload build artifacts
